# yaml-language-server: $schema=https://bitbucket.org/atlassianlabs/intellij-bitbucket-references-plugin/raw/master/src/main/resources/schemas/bitbucket-pipelines.schema.json

# Bitbucket Pipeline YAML Schema documentation
# https://support.atlassian.com/bitbucket-cloud/docs/bitbucket-pipelines-configuration-reference/

image: atlassian/default-image:4

pipelines:
  branches:
    main:
      - step:
          name: Trigger root-cdk pipeline
          script:
            - pipe: atlassian/trigger-pipeline:5.8.1
              variables:
                BITBUCKET_ACCESS_TOKEN: $BITBUCKET_ACCESS_TOKEN
                REPOSITORY: 'root-cdk'
                REF_TYPE: 'branch'
                REF_NAME: 'main'
                CUSTOM_PIPELINE_NAME: 'web-app'
